### ISSUE TITLE
Expand README with build / test / deploy information

### ISSUE THREAD

**Issue by andypiper** [codepope/makeroni#3]
At the moment all I know is that this is a Hugo site running on Netlify.

Could the README be expanded to cover how to build and test locally? It would be very helpful for new contributors.

**Comment by codepope** [comment]
Added basic instructions - leaving open if we need more.

**Comment by andypiper** [comment]
This worked for me so far, so I'm happy to close this for now. Can be expanded as needed - likely to be the case as we add membership setup etc.
